### ISSUE TITLE
Test: Implement Health Bar for Player and Health System

### ISSUE THREAD

**Issue by robert-beall** [jdoiron94/Outside-The-Box#11]
Player health should be represented onscreen. 
Player health should decrease from damage and increase over time.

**Comment by Femista** [comment]
Works, just need to test against enemies.

**Comment by jdoiron94** [comment]
PlayerManager's methods and stuff dealing with display bars/mana/hp should go in the Entity class, since it is not exclusive to the player. Entity already has support for health; just add the mana, experience, and display bars. Then, remove the PlayerManager instance from InputManager. To regenerate health, deriveHealth(x); deriveHealth(-x) to cause damage. Also, you'll be able to just call displayBar.Width = width instead of creating a local copy of the bar, updating its width, and then setting the new memory address. It's more efficient.

**Comment by robert-beall** [comment]
I'm not convinced we should have the player be an entity which is why I made a separate class. Enemies won't necessarily have the same amount of health, any mana, or experience. They also won't have display bars. The player character will also likely need a list of powers, unless we will have a separate class handling powers, a class handling xp, and so on and so forth. What do you think?

**Comment by jdoiron94** [comment]
We could easily do it as Entities. I'm more than likely going to simplify the Entity class soon anyway. The constructor holds too much information to really be viable without looking silly. If we did it the Entity way, we'd just have to make a few more variables and use set methods to set abilities, mana, etc. In this way, entities won't be given powers, mana, or anything, since they'll default to null values.

**Comment by robert-beall** [comment]
Good point, if you want I can make the modifications during Software Engineering.

**Comment by jdoiron94** [comment]
Should be ready to test.

**Comment by Femista** [comment]
Works well, but we'll discuss if it should regenerate faster.
