### ISSUE TITLE
Test: Enemy Aggressiveness 

### ISSUE THREAD

**Issue by robert-beall** [jdoiron94/Outside-The-Box#8]
Enemies should be able to fire projectiles at player and path to the player.

**Comment by jdoiron94** [comment]
Should be ready to test.

**Comment by Femista** [comment]
Works, but A. Should be able to be used while moving. B. Should only be firing when in front of you, and should move around to try and get in front of you to fire. Also should probably do more damage and fire less shots. Also the bullets affect the other npc, as it disappeared after a while of being shot. There should also be an out of range function, so it stop firing and following once it gets far enough away.

**Comment by jdoiron94** [comment]
That was just a base for future upgrades. Some enemies will simply patrol (like the one Goku that just wanders its predefined rectangle) - as stealth is going to be the key to solving the first level. Getting caught will reset the player. Other enemies will be given origins and will be able to wander freely within a predefined area, while firing at the player. A few will just be stationary and shoot if the player comes close.

Currently, it works via a radius. When within the radius, it faces the player and then just pre-fires. When outside, it stops shooting. It's currently set to 250 pixels. I'm going to change it to fire within a sub-radius of the specified radius, to be more precise and have it spam less. It does have support for firing fewer shots, with the cooldown in the Projectile class. Damage will just need to be scaled by their level in the corresponding ability (that'll change once they get added). I left bullets killing the NPC because that's realistic. But, I will change it so that it avoids shooting when other NPCs are within a certain distance and it's aiming their way.
